# Generated by Django 2.2 on 2019-06-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190622_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='direction',
            field=models.CharField(choices=[('на русский', 'на русский'), ('с русского', 'с русского')], default='на русский', max_length=255, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='training',
            name='mode',
            field=models.CharField(choices=[('все слова', 'все слова'), ('неизученные', 'неизученные')], default='все слова', max_length=255, verbose_name='Режим'),
        ),
    ]
