# Generated by Django 2.2 on 2019-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190622_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[('en', 'Английский'), ('fr', 'Французский')], default='en', max_length=10, verbose_name='Код'),
        ),
    ]
